### ISSUE TITLE
Editor: Multiple graph panels remove graph render from each other

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/FUDGE#311]
When dragging the same graph into a second graph panel the graph render from the first panel will stop displaying anything (only noticeable after triggering a redraw in first render graph).

**Comment by JirkaDellOro** [comment]
Hm... thinking about it, I guess it's not a side-effect of the changes to the event-pump, but of an earlier one. In order to illuminate a graph that does not contain lights, the graph gets inserted into the view as a child of a parent node that has some light to be switched on and off. Opening another view will switch the parent of the graph, since it can't have multiple parents.

I have to think about how I can illuminate differently... :-(

**Comment by JirkaDellOro** [comment]
Ok, I came up with a different solution and implemented it in devJirka. Please merge and test.

**Comment by plojo** [comment]
Ok seems to work so far, keeping an eye on it.

**Comment by JirkaDellOro** [comment]
Neue Erkenntnisse? Sonst würde ich integrieren.

**Comment by plojo** [comment]
Habe keine Fehler mehr bemerkt.
